name: oyt_admin
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  collection: ^1.16.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.1
  font_awesome_flutter: ^10.3.0
  go_router: ^5.2.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  lottie: ^2.0.0
  mobile_scanner: ^2.1.0
  riverpod: ^2.1.1
  oyt_front_core:
    path: ./packages/oyt_front_core
  oyt_front_widgets:
    path: ./packages/oyt_front_widgets
  oyt_front_auth:
    path: ./packages/oyt_front_auth
  oyt_front_restaurant:
    path: ./packages/oyt_front_restaurant
  oyt_front_product:
    path: ./packages/oyt_front_product
  oyt_front_order:
    path: ./packages/oyt_front_order
  oyt_front_table:
    path: ./packages/oyt_front_table
  oyt_front_menu:
    path: ./packages/oyt_front_menu
  oyt_front_orders_queue:
    path: ./packages/oyt_front_orders_queue
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  firebase_messaging_web: ^3.2.9
  firebase_core_web: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
