name: oyt_admin
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  oyt_front_core:
    path: ./packages/oyt_front_core
  oyt_front_widgets:
    path: ./packages/oyt_front_widgets
  oyt_front_auth:
    path: ./packages/oyt_front_auth
  oyt_front_restaurant:
    path: ./packages/oyt_front_restaurant
  oyt_front_product:
    path: ./packages/oyt_front_product
  oyt_front_order:
    path: ./packages/oyt_front_order
  oyt_front_table:
    path: ./packages/oyt_front_table
  oyt_front_menu:
    path: ./packages/oyt_front_menu
  oyt_front_orders_queue:
    path: ./packages/oyt_front_orders_queue
  qr_flutter: ^4.0.0
  share_plus: ^6.3.1
  share_plus_web: ^3.1.0
  download: ^1.0.0
  fl_chart: ^0.60.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
